export enum PermissionStatus {
    CHECKING = 'CHECKING',
    GRANTED = 'GRANTED',
    DENIED = 'DENIED',
    BLOCKED = 'BLOCKED',
    LIMITED = 'LIMITED',
    UNAVAILABLE = 'UNAVAILABLE',
    UNDETERMINED = 'UNDETERMINED',
}